# Generated by Django 5.2.3 on 2025-07-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rock',
            old_name='tpye',
            new_name='type',
        ),
    ]
